/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/exception/403.vue')['default']
    404: typeof import('./src/components/exception/404.vue')['default']
    500: typeof import('./src/components/exception/500.vue')['default']
    Buttons: typeof import('./src/components/exception/buttons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}

// For TSX support
declare global {
  const 403: typeof import('./src/components/exception/403.vue')['default']
  const 404: typeof import('./src/components/exception/404.vue')['default']
  const 500: typeof import('./src/components/exception/500.vue')['default']
  const Buttons: typeof import('./src/components/exception/buttons.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
  const Router: typeof import('./src/components/layout/Router.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
}