/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/exception/403.vue')['default']
    404: typeof import('./src/components/exception/404.vue')['default']
    500: typeof import('./src/components/exception/500.vue')['default']
    Buttons: typeof import('./src/components/exception/buttons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
  }
}

// For TSX support
declare global {
  const 403: typeof import('./src/components/exception/403.vue')['default']
  const 404: typeof import('./src/components/exception/404.vue')['default']
  const 500: typeof import('./src/components/exception/500.vue')['default']
  const Buttons: typeof import('./src/components/exception/buttons.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
  const Router: typeof import('./src/components/layout/Router.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
  const TButton: typeof import('tdesign-mobile-vue')['Button']
  const TCell: typeof import('tdesign-mobile-vue')['Cell']
  const TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
  const TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
  const TForm: typeof import('tdesign-mobile-vue')['Form']
  const TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
  const TIcon: typeof import('tdesign-mobile-vue')['Icon']
  const TImage: typeof import('tdesign-mobile-vue')['Image']
  const TInput: typeof import('tdesign-mobile-vue')['Input']
  const TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
  const TSearch: typeof import('tdesign-mobile-vue')['Search']
  const TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
  const TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
  const TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
  const TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
  const TTable: typeof import('tdesign-mobile-vue')['Table']
  const TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
  const TTabs: typeof import('tdesign-mobile-vue')['Tabs']
  const TTag: typeof import('tdesign-mobile-vue')['Tag']
}